### ISSUE TITLE
bufferlist: numbers shown as "x.0" on lua 5.3

### ISSUE THREAD

**Issue by jansol** [tomoe-mami/weechat-scripts#4] opened 2016-10-26 09:33 UTC
Looks like whatever is used for numbers in the bufferlist (both buffer number and unread count) is printed as float/double when using lua5.3

**Comment by tomoe-mami** [comment] 2016-10-26 14:52
The problem is not the script. I asked @FlashCode [about this before][1]. After asking other people who are familiar with Lua, what I've gathered are:

1. Lua 5.3 introduced integer only value
2. `pushnumber` now always pushes float value and `pushinteger` pushes integer value. [Weechat uses `pushnumber` for all integers][2].
3. Lua 5.3 keeps the fractional part when converting float to string

I [wrote a fix for this][3]. It works and it's the Weechat I'm using but I'm not confidence enough to submit it as PR because I've never done C before.

I'll try asking FlashCode again about this.

[1]: http://sprunge.us/iaOO
[2]: https://github.com/weechat/weechat/blob/master/src/plugins/lua/weechat-lua-api.c#L85-L90
[3]: https://github.com/tomoe-mami/weechat/commit/940e5e62e6bb22f8446bf7c7c90f9272ee3b3e4b

**Comment by flashcode** [comment] 2016-10-28 11:32
@tomoe-mami: please submit this patch as pull request for weechat, I'll test and merge it.
Please mention in the pull request how to reproduce the problem.

**Comment by tomoe-mami** [comment] 2016-11-02 00:04
It's fixed in weechat/weechat@899b397f3f5d04c5f34ef8b964f9395e34cbff14 so I'm closing this.

**Closed by tomoe-mami** 2016-11-02 00:04 UTC
